# Generated by Django 4.0.1 on 2022-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('hash_id', models.TextField()),
                ('hash_key', models.TextField()),
                ('number', models.CharField(max_length=120)),
                ('session_file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('group_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('questions', models.TextField()),
            ],
        ),
    ]
