# Generated by Django 4.0.1 on 2022-03-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0003_telegram_accounts_sleep_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('account_id', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('delay', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
