# Generated by Django 4.0.3 on 2022-03-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramBot', '0004_schedule_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule_Messages',
        ),
    ]
